// Generated by CoffeeScript 1.7.1
(function() {
  var timer;

  window.load = function() {
    return timer;
  };

  timer = setInterval(function() {});

}).call(this);

//# sourceMappingURL=CoffeeScript.js.map